'use strict';
const express=require('express');const db=require('../db');const {requirePermission}=require('../rbac');const {hashPassword}=require('../crypto');const {audit}=require('../audit');const router=express.Router();
router.get('/active',requirePermission('reports.read'),async(req,res,next)=>{try{const q=await db.query(`SELECT u.id,u.display_name,r.name role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.is_active=true ORDER BY u.display_name`);res.json({users:q.rows});}catch(e){next(e)}});
router.get('/',requirePermission('accessAdmin'),async(req,res,next)=>{try{const q=await db.query(`SELECT u.id,u.email,u.display_name,u.is_active,u.mfa_required,r.name role,u.created_at,u.updated_at FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.display_name`);res.json({users:q.rows});}catch(e){next(e)}});
router.post('/',requirePermission('accessAdmin'),async(req,res,next)=>{try{const b=req.body||{};if(!b.email||!b.displayName||!b.role||String(b.password||'').length<12)return res.status(400).json({detail:'Email, display name, role and a password of at least 12 characters are required.'});const role=(await db.query('SELECT id FROM roles WHERE name=$1',[b.role])).rows[0];if(!role)return res.status(400).json({detail:'Unknown role.'});const hash=await hashPassword(String(b.password));const q=await db.query(`INSERT INTO users(email,display_name,role_id,password_hash,mfa_required,password_changed_at) VALUES(lower($1),$2,$3,$4,$5,now()) RETURNING id,email,display_name,is_active,mfa_required,created_at`,[b.email,b.displayName,role.id,hash,!!b.mfaRequired]);await audit(db,{actorUserId:req.user.id,eventType:'user.create',objectType:'user',objectId:q.rows[0].id,metadata:{role:b.role}});res.status(201).json({user:{...q.rows[0],role:b.role}});}catch(e){next(e)}});

router.patch('/:id',requirePermission('accessAdmin'),async(req,res,next)=>{try{const b=req.body||{};let roleId=null;if(b.role){const rr=await db.query('SELECT id FROM roles WHERE name=$1',[b.role]);if(!rr.rowCount)return res.status(400).json({detail:'Unknown role.'});roleId=rr.rows[0].id;}let passwordHash=null;if(b.password!==undefined){if(String(b.password).length<12)return res.status(400).json({detail:'New password must be at least 12 characters.'});passwordHash=await hashPassword(String(b.password));}const q=await db.query(`UPDATE users SET display_name=COALESCE($2,display_name),role_id=COALESCE($3,role_id),is_active=COALESCE($4,is_active),mfa_required=COALESCE($5,mfa_required),password_hash=COALESCE($6,password_hash),password_changed_at=CASE WHEN $6 IS NOT NULL THEN now() ELSE password_changed_at END,updated_at=now() WHERE id=$1 RETURNING id,email,display_name,is_active,mfa_required,created_at,updated_at`,[req.params.id,b.displayName||null,roleId,b.isActive===undefined?null:!!b.isActive,b.mfaRequired===undefined?null:!!b.mfaRequired,passwordHash]);if(!q.rowCount)return res.status(404).json({detail:'User not found.'});if(b.isActive===false||passwordHash)await db.query('DELETE FROM sessions WHERE user_id=$1',[req.params.id]);await audit(db,{actorUserId:req.user.id,eventType:'user.update',objectType:'user',objectId:req.params.id,metadata:{role:b.role||undefined,isActive:b.isActive}});res.json({user:q.rows[0]});}catch(e){next(e)}});
router.get('/:id/sessions',requirePermission('accessAdmin'),async(req,res,next)=>{try{const q=await db.query(`SELECT id,created_at,last_seen_at,idle_expires_at,absolute_expires_at,ip_address,user_agent FROM sessions WHERE user_id=$1 ORDER BY last_seen_at DESC`,[req.params.id]);res.json({sessions:q.rows});}catch(e){next(e)}});
router.delete('/:id/sessions',requirePermission('accessAdmin'),async(req,res,next)=>{try{const q=await db.query('DELETE FROM sessions WHERE user_id=$1',[req.params.id]);await audit(db,{actorUserId:req.user.id,eventType:'user.sessions.revoke',objectType:'user',objectId:req.params.id,metadata:{revoked:q.rowCount}});res.json({revoked:q.rowCount});}catch(e){next(e)}});
module.exports=router;
