(()=>{'use strict';
const C={csrf:'',user:null};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function session(){if(C.user)return C;const r=await fetch('/api/auth/me',{credentials:'same-origin'});if(r.status===401){location.href='/staff/login.html?next='+encodeURIComponent(location.pathname+location.search);throw new Error('Authentication required');}if(!r.ok)throw new Error('Unable to verify staff session');const d=await r.json();C.user=d.user;C.csrf=d.csrf||'';sessionStorage.setItem('smg_v43_csrf',C.csrf);return C}
async function api(path,opt={}){await session();const o={credentials:'same-origin',...opt};o.headers={...(opt.headers||{})};if(o.body && !(o.body instanceof FormData)){o.headers['Content-Type']=o.headers['Content-Type']||'application/json';if(typeof o.body!=='string')o.body=JSON.stringify(o.body)}if(!['GET','HEAD'].includes((o.method||'GET').toUpperCase()))o.headers['X-SMG-CSRF']=C.csrf;let r=await fetch(path,o);if(r.status===401){C.user=null;location.href='/staff/login.html?next='+encodeURIComponent(location.pathname);throw new Error('Session expired')}let d=null;const ct=r.headers.get('content-type')||'';if(ct.includes('json'))d=await r.json();else d=await r.text();if(!r.ok)throw new Error(d?.detail||`Request failed (${r.status})`);return d}
function val(id){const e=document.getElementById(id);return e?e.value.trim():''}function set(id,v){const e=document.getElementById(id);if(e)e.value=v??''}function msg(text,kind=''){const e=document.getElementById('msg');if(e){e.textContent=text;e.className='notice '+kind}}
function fmt(v){if(!v)return '—';try{return new Date(v).toLocaleString('en-TT',{dateStyle:'medium',timeStyle:v.includes?.('T')?'short':undefined})}catch{return v}}
async function init(){try{const s=await session();document.querySelectorAll('[data-auth]').forEach(e=>e.innerHTML=`${esc(s.user.name||s.user.email)} · ${esc(s.user.role)} <button id="logoutBtn">Sign out</button>`);const b=document.getElementById('logoutBtn');if(b)b.onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}finally{location.href='/staff/login.html'}}}catch(e){}}
window.SMG={api,session,esc,val,set,msg,fmt,state:C};document.addEventListener('DOMContentLoaded',init);
})();