'use strict';
const fs=require('fs/promises');const path=require('path');const crypto=require('crypto');const config=require('./config');
let s3Client=null;
function s3Ready(){const s=config.s3;return !!(s.bucket&&s.accessKeyId&&s.secretAccessKey);}
async function s3(){if(s3Client)return s3Client;const {S3Client}=require('@aws-sdk/client-s3');s3Client=new S3Client({region:config.s3.region,endpoint:config.s3.endpoint||undefined,forcePathStyle:config.s3.forcePathStyle,credentials:{accessKeyId:config.s3.accessKeyId,secretAccessKey:config.s3.secretAccessKey}});return s3Client;}
async function ensureReady(){if(config.storageDriver==='local'){if(config.production&&!config.allowLocalPrivateStorage)throw new Error('Local private storage is intentionally disabled in production.');await fs.mkdir(config.storagePath,{recursive:true});return;}if(config.storageDriver==='s3'){if(!s3Ready())throw new Error('S3-compatible private storage is not fully configured.');return;}throw new Error('Unknown private storage driver.');}
async function saveBuffer(buffer,originalName,mimeType='application/octet-stream'){await ensureReady();const id=crypto.randomUUID(),safeExt=path.extname(originalName||'').replace(/[^.A-Za-z0-9]/g,'').slice(0,10),key=`documents/${new Date().getUTCFullYear()}/${id}${safeExt}`,sha256=crypto.createHash('sha256').update(buffer).digest('hex');if(config.storageDriver==='local'){const localKey=key.replaceAll('/','__');await fs.writeFile(path.join(config.storagePath,localKey),buffer,{flag:'wx',mode:0o600});return {key:localKey,sha256,sizeBytes:buffer.length};}const {PutObjectCommand}=require('@aws-sdk/client-s3');await (await s3()).send(new PutObjectCommand({Bucket:config.s3.bucket,Key:key,Body:buffer,ContentType:mimeType,Metadata:{sha256}}));return {key,sha256,sizeBytes:buffer.length};}
async function readBuffer(key){await ensureReady();if(config.storageDriver==='local'){if(!/^[A-Za-z0-9_.-]+$/.test(key))throw new Error('Invalid storage key.');return fs.readFile(path.join(config.storagePath,key));}const {GetObjectCommand}=require('@aws-sdk/client-s3');const r=await (await s3()).send(new GetObjectCommand({Bucket:config.s3.bucket,Key:key}));return Buffer.from(await r.Body.transformToByteArray());}
function readiness(){if(config.storageDriver==='local')return !config.production||config.allowLocalPrivateStorage;if(config.storageDriver==='s3')return s3Ready();return false;}
module.exports={ensureReady,saveBuffer,readBuffer,readiness};
